# Amazon rerank/cache settings

mode: aspects   # aspects|summary (formerly component)
fields: "N,D,I,R"  # persona fields for persona cache (N=Name, D=Description, I=item_summary, R=Preference_Rationale)
alpha: 0.85
user_max_k: 10
num_gpus: 1

# If you want to reuse existing caches, set use_external_caches to 1 and fill ext_* paths
use_external_caches: 0
ext_persona_cache: ""
ext_interaction_cache: ""

